# Generated by Django 2.0.13 on 2020-01-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dane_uzytkownika',
            fields=[
                ('ID_uzytkownika', models.IntegerField(primary_key=True, serialize=False)),
                ('Imie_uzytkownika', models.CharField(max_length=45)),
                ('Nazwisko_uzytkownika', models.CharField(max_length=45)),
                ('Wiek', models.IntegerField()),
                ('Miejscowosc', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zainteresowania',
            fields=[
                ('ID_zainteresowania', models.IntegerField(primary_key=True, serialize=False)),
                ('Zainteresowanie', models.CharField(max_length=45)),
                ('ID_uzytkownika', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Znajomi',
            fields=[
                ('ID_znajomego', models.IntegerField(primary_key=True, serialize=False)),
                ('Zainteresowania', models.CharField(max_length=45)),
                ('Wiek', models.IntegerField()),
                ('Miejscowosc', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Znajomi_has_zainteresowania_uzytkownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zainteresowania_uzytkownika_ID_zainteresowania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.Zainteresowania')),
                ('Znajomi_ID_znajomego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.Znajomi')),
            ],
        ),
        migrations.AddField(
            model_name='dane_uzytkownika',
            name='Zainteresowania_ID_zainteresowania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzytkownicy.Zainteresowania'),
        ),
    ]
